import { StyleItem } from '../utils/imageUtils';

export const stylesList: StyleItem[] = [
  { 
    id: 1, 
    DisplayName: "Anime",
    name: 'Anime', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743390806/cooylozjk3ssauku8jer.png',
    category: 'Animation',
  },
  { 
    id: 8, 
    DisplayName: "Lego",
    name: 'Lego', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743896925/r0qvqqucbuyqocqxugvr.png',
    category: 'Animation',
  },
  { 
    id: 6, 
    DisplayName: "OldSchool Anime",
    name: 'OldSchool', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743487089/kxvubooxncxuxggxs8bk.png',
    category: 'Animation',
  },
  { 
    id: 2, 
    DisplayName: "Cartoon",
    name: 'Cartoon', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744134965/tnccymhqprvsrlglhyyz.png',
    category: 'Animation',
  },
  { 
    id: 3, 
    DisplayName: "threeD",
    name: 'threeD', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743295994/Screenshot_2025-03-29_190345_gk19da.png',
    category: 'Animation',
  },
  { 
    id: 4, 
    DisplayName: "Retro",
    name: 'Retro', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743487416/w05w3temili6a8izc9vv.png',
    category: 'Animation',
  },
  { 
    id: 5, 
    DisplayName: "Chibli",
    name: 'ghibliStyle', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743390195/pnlywxojs1bn4m9ad6b5.png',
    category: 'Animation',
  },

  { 
    id: 7, 
    DisplayName: "Simpsons",
    name: 'Simpsons', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1743896840/yxyhnq1wsrabf2prkqct.png',
    category: 'Animation',
  },
 
  { 
    id: 9, 
    DisplayName: "Rick And Morty",
    name: 'RickAndMorty', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744134300/atnsugn7eyixjydumqqq.png',
    category: 'Animation',
  },
  { 
    id: 10, 
    DisplayName: "SouthPark",
    name: 'SouthPark', 
    src: 'https://variety.com/wp-content/uploads/2021/04/South-Park-Key-Art.jpg?w=1000&h=562&crop=1',
    category: 'Animation',
  },
  { 
    id: 11, 
    DisplayName: "Cyberpunk",
    name: 'Cyberpunk', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744134965/aki4og2mclmhai2aj9qg.png',
    category: 'Animation',
  },
  { 
    id: 13, 
    DisplayName: "Steampunk",
    name: 'Steampunk', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744133983/ehrbcdmxgxdliqfsdtqr.png',
    category: 'Animation',
  },
  { 
    id: 15, 
    DisplayName: "Historical Portrait",
    name: 'HistoricalPortrait', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744138287/ywxru5z4kmneovn2oyii.png',
    category: 'Animation',
  },
  { 
    id: 16, 
    DisplayName: "Movie Poster",
    name: 'MoviePoster', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744138299/arpe5spyf8fgej3ggty6.png',
    category: 'Animation',
  },
  { 
    id: 17, 
    DisplayName: "Professional Headshot",
    name: 'ProfessionalHeadshot', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744133983/aumbvdy2yibsliibluoy.png',
    category: 'Animation',
  },
  { 
    id: 18, 
    DisplayName: "Comic Book",
    name: 'ComicBook', 
    src: 'https://res.cloudinary.com/dzvttwdye/image/upload/v1744138298/zai69xmcohun0rvwonvm.png',
    category: 'Animation',
  },
];